// 2026 NCAA Tournament Data — Men's & Women's Brackets
// slots order per region: 1,16,8,9, 5,12,4,13, 6,11,3,14, 7,10,2,15

const TOURNAMENTS = {
  men: {
    name: "Men's NCAA Tournament",
    shortName: "Men's",
    year: 2026,
    firstFour: [
      { id: 'mff1', region: 'West',    seed: 11, team1: 'Texas',            team2: 'NC State' },
      { id: 'mff2', region: 'Midwest', seed: 16, team1: 'UMBC',             team2: 'Howard' },
      { id: 'mff3', region: 'Midwest', seed: 11, team1: 'Miami (OH)',       team2: 'SMU' },
      { id: 'mff4', region: 'South',   seed: 16, team1: 'Prairie View A&M', team2: 'Lehigh' },
    ],
    regions: [
      {
        id: 'east', name: 'East', color: '#1e3a8a',
        slots: [
          { seed: 1,  name: 'Duke' },
          { seed: 16, name: 'Siena' },
          { seed: 8,  name: 'Ohio State' },
          { seed: 9,  name: 'TCU' },
          { seed: 5,  name: "St. John's" },
          { seed: 12, name: 'Northern Iowa' },
          { seed: 4,  name: 'Kansas' },
          { seed: 13, name: 'Cal Baptist' },
          { seed: 6,  name: 'Louisville' },
          { seed: 11, name: 'South Florida' },
          { seed: 3,  name: 'Michigan State' },
          { seed: 14, name: 'North Dakota State' },
          { seed: 7,  name: 'UCLA' },
          { seed: 10, name: 'UCF' },
          { seed: 2,  name: 'UConn' },
          { seed: 15, name: 'Furman' },
        ],
      },
      {
        id: 'west', name: 'West', color: '#7c3aed',
        slots: [
          { seed: 1,  name: 'Arizona' },
          { seed: 16, name: 'LIU' },
          { seed: 8,  name: 'Villanova' },
          { seed: 9,  name: 'Utah State' },
          { seed: 5,  name: 'Wisconsin' },
          { seed: 12, name: 'High Point' },
          { seed: 4,  name: 'Arkansas' },
          { seed: 13, name: 'Hawaii' },
          { seed: 6,  name: 'BYU' },
          { seed: 11, name: 'TBD', firstFourId: 'mff1' }, // Texas vs NC State
          { seed: 3,  name: 'Gonzaga' },
          { seed: 14, name: 'Kennesaw State' },
          { seed: 7,  name: 'Miami (FL)' },
          { seed: 10, name: 'Missouri' },
          { seed: 2,  name: 'Purdue' },
          { seed: 15, name: 'Queens' },
        ],
      },
      {
        id: 'midwest', name: 'Midwest', color: '#b45309',
        slots: [
          { seed: 1,  name: 'Michigan' },
          { seed: 16, name: 'TBD', firstFourId: 'mff2' }, // UMBC vs Howard
          { seed: 8,  name: 'Georgia' },
          { seed: 9,  name: 'Saint Louis' },
          { seed: 5,  name: 'Texas Tech' },
          { seed: 12, name: 'Akron' },
          { seed: 4,  name: 'Alabama' },
          { seed: 13, name: 'Hofstra' },
          { seed: 6,  name: 'Tennessee' },
          { seed: 11, name: 'TBD', firstFourId: 'mff3' }, // Miami (OH) vs SMU
          { seed: 3,  name: 'Virginia' },
          { seed: 14, name: 'Wright State' },
          { seed: 7,  name: 'Kentucky' },
          { seed: 10, name: 'Santa Clara' },
          { seed: 2,  name: 'Iowa State' },
          { seed: 15, name: 'Tennessee State' },
        ],
      },
      {
        id: 'south', name: 'South', color: '#065f46',
        slots: [
          { seed: 1,  name: 'Florida' },
          { seed: 16, name: 'TBD', firstFourId: 'mff4' }, // Prairie View A&M vs Lehigh
          { seed: 8,  name: 'Clemson' },
          { seed: 9,  name: 'Iowa' },
          { seed: 5,  name: 'Vanderbilt' },
          { seed: 12, name: 'McNeese' },
          { seed: 4,  name: 'Nebraska' },
          { seed: 13, name: 'Troy' },
          { seed: 6,  name: 'North Carolina' },
          { seed: 11, name: 'VCU' },
          { seed: 3,  name: 'Illinois' },
          { seed: 14, name: 'Penn' },
          { seed: 7,  name: "Saint Mary's" },
          { seed: 10, name: 'Texas A&M' },
          { seed: 2,  name: 'Houston' },
          { seed: 15, name: 'Idaho' },
        ],
      },
    ],
    // SF1: East vs South  |  SF2: West vs Midwest
    finalFourPairs: [[0, 3], [1, 2]],
  },

  women: {
    name: "Women's NCAA Tournament",
    shortName: "Women's",
    year: 2026,
    firstFour: [
      { id: 'wff1', region: 'UCLA',          seed: 11, team1: 'Nebraska',     team2: 'Richmond' },
      { id: 'wff2', region: 'South Carolina', seed: 16, team1: 'Southern',     team2: 'Samford' },
      { id: 'wff3', region: 'South Carolina', seed: 10, team1: 'Virginia',     team2: 'Arizona State' },
      { id: 'wff4', region: 'Texas',          seed: 16, team1: 'Missouri State', team2: 'Stephen F. Austin' },
    ],
    regions: [
      {
        id: 'uconn', name: 'UConn Region', color: '#002868',
        slots: [
          { seed: 1,  name: 'UConn' },
          { seed: 16, name: 'UTSA' },
          { seed: 8,  name: 'Iowa State' },
          { seed: 9,  name: 'Syracuse' },
          { seed: 5,  name: 'Maryland' },
          { seed: 12, name: 'Murray State' },
          { seed: 4,  name: 'North Carolina' },
          { seed: 13, name: 'Western Illinois' },
          { seed: 6,  name: 'Notre Dame' },
          { seed: 11, name: 'Fairfield' },
          { seed: 3,  name: 'Ohio State' },
          { seed: 14, name: 'Howard' },
          { seed: 7,  name: 'Illinois' },
          { seed: 10, name: 'Colorado' },
          { seed: 2,  name: 'Vanderbilt' },
          { seed: 15, name: 'High Point' },
        ],
      },
      {
        id: 'ucla', name: 'UCLA Region', color: '#2D68C4',
        slots: [
          { seed: 1,  name: 'UCLA' },
          { seed: 16, name: 'Cal Baptist' },
          { seed: 8,  name: 'Oklahoma State' },
          { seed: 9,  name: 'Princeton' },
          { seed: 5,  name: 'Ole Miss' },
          { seed: 12, name: 'Gonzaga' },
          { seed: 4,  name: 'Minnesota' },
          { seed: 13, name: 'Green Bay' },
          { seed: 6,  name: 'Baylor' },
          { seed: 11, name: 'TBD', firstFourId: 'wff1' }, // Nebraska vs Richmond
          { seed: 3,  name: 'Duke' },
          { seed: 14, name: 'Charleston' },
          { seed: 7,  name: 'Texas Tech' },
          { seed: 10, name: 'Villanova' },
          { seed: 2,  name: 'LSU' },
          { seed: 15, name: 'Jacksonville' },
        ],
      },
      {
        id: 'sc', name: 'South Carolina Region', color: '#73000A',
        slots: [
          { seed: 1,  name: 'South Carolina' },
          { seed: 16, name: 'TBD', firstFourId: 'wff2' }, // Southern vs Samford
          { seed: 8,  name: 'Clemson' },
          { seed: 9,  name: 'USC' },
          { seed: 5,  name: 'Michigan State' },
          { seed: 12, name: 'Colorado State' },
          { seed: 4,  name: 'Oklahoma' },
          { seed: 13, name: 'Idaho' },
          { seed: 6,  name: 'Washington' },
          { seed: 11, name: 'South Dakota State' },
          { seed: 3,  name: 'TCU' },
          { seed: 14, name: 'UC San Diego' },
          { seed: 7,  name: 'Georgia' },
          { seed: 10, name: 'TBD', firstFourId: 'wff3' }, // Virginia vs Arizona State
          { seed: 2,  name: 'Iowa' },
          { seed: 15, name: 'Fairleigh Dickinson' },
        ],
      },
      {
        id: 'texas', name: 'Texas Region', color: '#BF5700',
        slots: [
          { seed: 1,  name: 'Texas' },
          { seed: 16, name: 'TBD', firstFourId: 'wff4' }, // Missouri State vs SFA
          { seed: 8,  name: 'Oregon' },
          { seed: 9,  name: 'Virginia Tech' },
          { seed: 5,  name: 'Kentucky' },
          { seed: 12, name: 'James Madison' },
          { seed: 4,  name: 'West Virginia' },
          { seed: 13, name: 'Miami (OH)' },
          { seed: 6,  name: 'Alabama' },
          { seed: 11, name: 'Rhode Island' },
          { seed: 3,  name: 'Louisville' },
          { seed: 14, name: 'Vermont' },
          { seed: 7,  name: 'NC State' },
          { seed: 10, name: 'Tennessee' },
          { seed: 2,  name: 'Michigan' },
          { seed: 15, name: 'Holy Cross' },
        ],
      },
    ],
    // SF1: UConn region vs Texas region  |  SF2: UCLA region vs SC region
    finalFourPairs: [[0, 3], [1, 2]],
  },
};
